#!/usr/bin/env bash
git clone https://github.com/LangiviTechnology/fileio.git -b dev
cd fileio
cd rustlib
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -y
source $HOME/.cargo/env
apt-get install -y clang
cargo build
cd ..
phpize
make clean
./configure --with-uv
make
make install
cd ..
rm -rf fileio
echo "extension=fileio" > /usr/local/etc/php/conf.d/fileio.ini
