#!/usr/bin/env bash
git clone https://github.com/LangiviTechnology/fileio.git -b db-adoptation
cd fileio
phpize
make clean
./configure --with-uv
make
make install
cd ..
rm -rf fileio
echo "extension=fileio" > /usr/local/etc/php/conf.d/fileio.ini
