#!/usr/bin/env bash
#php  -dextension=fileio -m
#ENV
php  -dextension=fileio -dmemory_limit=512M -f ./stubs/index.php
#source=""
#for i in $(pwd)/functions/*/*.c ; do
#  file=$(echo $i | sed -e "s|$(pwd)/functions|\$FUNCTIONS|g")
#  source="$source $file"
#done
#echo $source