#!/usr/bin/env bash
#php  -dextension=fileio -m
#php  -dextension=fileio -f ./stubs/index.php
source=""
for i in $(pwd)/functions/*/*.c ; do
  file=$(echo $i | sed -e "s|$(pwd)/functions|\$FUNCTIONS|g")
  source="$source $file"
done
echo $source